Vagrant.configure("2") do |config|
  config.vm.box       = "centos-6.4-x86_64"
  config.vm.box_url   = "https://dl.dropboxusercontent.com/u/11604562/centos-6.4-x86_64.box"
  config.vm.hostname  = "centos6-vm"
  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.provider "virtualbox" do |v|
    #v.gui  = true # uncommenting this will create a console window while the machine is running, that you can't get rid of :-(
    v.name = "centos6-vm"
  end

  config.vm.synced_folder "stuff/", "/stuff", disabled: true

  config.vm.provision :shell, :path => "centos_6_x.sh"

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.module_path    = "modules"
    puppet.manifest_file  = "default.pp"
    puppet.options        = "--verbose --debug"
  end
end
