Vagrant.configure("2") do |config|
  config.vm.box       = "ubuntu-13.04-server-amd64"
  config.vm.box_url   = "https://www.dropbox.com/sh/dtgjde7mahmcqp8/nrqw9fSBiL/ubuntu-13.04-server-amd64.box"
  config.vm.hostname  = "ringtail-server"
  #config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.provider "virtualbox" do |v|
    #v.gui  = true
    v.name = "ringtail-server"
  end

  config.vm.synced_folder "puppet/", "/puppet", disabled: true

  config.vm.provision :shell, :path => "ubuntu.sh"
end
